---
version: '3.8'

networks:
  net-default:

volumes:
  data-graylog:
  data-els:
  data-mongo:

secrets:
  GRAYLOG_ROOT_PASSWORD_SHA2:
    file: ./graylog.d/secrets/GRAYLOG_ROOT_PASSWORD_SHA2.txt
  GRAYLOG_PASSWORD_SECRET:
    file: ./graylog.d/secrets/GRAYLOG_PASSWORD_SECRET.txt

services:
  mongo:
    image: mongo:5.0
    hostname: graylog-mongo
    volumes:
      - data-mongo:/data/db
    networks:
      net-default:
    restart: always
    deploy:
      restart_policy:
        condition: any

  els:
    image: elasticsearch:7.16.1
    hostname: graylog-els
    environment:
      http.host:      "0.0.0.0"
      transport.host: "localhost"
      network.host:   "0.0.0.0"
      ES_JAVA_OPTS:   "-Xms1024m -Xmx1024m"
    networks:
      net-default:
    volumes:
      - data-els:/usr/share/elasticsearch/data
    restart: always
    deploy:
      restart_policy:
        condition: any

  graylog:
    image: graylog/graylog:5.0
    hostname: graylog-node
    volumes:
      - data-graylog:/usr/share/graylog/data/journal
    logging:
      driver: "json-file"
      options:
        max-size: "1024M"
        max-file: "1"
    secrets:
      - GRAYLOG_ROOT_PASSWORD_SHA2
      - GRAYLOG_PASSWORD_SECRET
    networks:
      net-default:
    ports:
      - 9000:9000
      - 12201:12201/tcp
      - 12201:12201/udp
    environment:
      GRAYLOG_ROOT_TIMEZONE:            "${GRAYLOG_ROOT_TIMEZONE:-Europe/Moscow}"
      GRAYLOG_ELASTICSEARCH_HOSTS:      "${GRAYLOG_ELASTICSEARCH_HOSTS:-http://els:9200}"
      GRAYLOG_MONGODB_URI:              "${GRAYLOG_MONGODB_URI:-mongodb://mongo/graylog}"
      GRAYLOG_ROOT_PASSWORD_SHA2__FILE: "${GRAYLOG_ROOT_PASSWORD_SHA2__FILE:-/run/secrets/GRAYLOG_ROOT_PASSWORD_SHA2}"
      GRAYLOG_PASSWORD_SECRET__FILE:    "${GRAYLOG_PASSWORD_SECRET__FILE:-/run/secrets/GRAYLOG_PASSWORD_SECRET}"
      GRAYLOG_HTTP_EXTERNAL_URI:        "${GRAYLOG_HTTP_EXTERNAL_URI}"

    restart: always
    deploy:
      restart_policy:
        condition: any
      update_config:
        order: stop-first

